// Dummy data used as fallbacks when backend is unavailable

export const DUMMY_DOCUMENTS = [
  {
    id: 'doc-001',
    name: 'Clinical Trial Protocol v2.1',
    original_filename: 'clinical-trial-protocol-v2.1.pdf',
    compliance_score: 92,
    status: 'completed',
    guidelines: ['ICH-E6', 'FDA-GCP'],
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    page_count: 48,
    file_size: 2456789,
  },
  {
    id: 'doc-002',
    name: 'Drug Safety Report Q3 2024',
    original_filename: 'drug-safety-q3-2024.pdf',
    compliance_score: null,
    status: 'processing',
    guidelines: ['ICH-E3'],
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    page_count: 127,
    file_size: 8923412,
  },
  {
    id: 'doc-003',
    name: 'ICH E6 Compliance Audit Report',
    original_filename: 'ich-e6-audit-2024.pdf',
    compliance_score: 85,
    status: 'completed',
    guidelines: ['ICH-E6', 'CDSCO-CT'],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    page_count: 32,
    file_size: 1234567,
  },
  {
    id: 'doc-004',
    name: 'FDA Label Review Package',
    original_filename: 'fda-label-review.pdf',
    compliance_score: 71,
    status: 'completed',
    guidelines: ['FDA-LABEL'],
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    page_count: 22,
    file_size: 987654,
  },
  {
    id: 'doc-005',
    name: 'Phase 3 Study Final Report',
    original_filename: 'phase3-study-final.pdf',
    compliance_score: null,
    status: 'failed',
    guidelines: ['ICH-E3', 'FDA-GCP'],
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    page_count: 215,
    file_size: 15678902,
  },
];

export const DUMMY_FINDINGS = [
  {
    id: 'find-001',
    document_id: 'doc-001',
    severity: 'critical',
    status: 'pending',
    section: 'Section 5.2 - Informed Consent',
    title: 'Informed Consent Missing Witness Signature Block',
    document_text:
      'The informed consent form shall be signed by the participant and the investigator prior to study enrollment.',
    regulatory_text:
      'ICH E6(R2) Section 4.8.8: Prior to a subject\'s participation in the trial, the written informed consent form should be signed and personally dated by the subject or by the subject\'s legally acceptable representative, and by the person who conducted the informed consent discussion.',
    citation: 'ICH E6(R2) § 4.8.8',
    gap_analysis:
      'The consent form lacks a witness signature block required under ICH E6(R2) and FDA 21 CFR 50.27. This constitutes a major deviation from GCP requirements and may invalidate consent obtained for enrolled subjects.',
    suggested_fix:
      'Add a witness signature line to the ICF with the following text: "Witness (if applicable): I confirm that the subject was provided adequate time and information to consider participation. Signature: ___ Date: ___"',
    confidence: 'HIGH',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'find-002',
    document_id: 'doc-001',
    severity: 'critical',
    status: 'pending',
    section: 'Section 8.1 - Safety Monitoring',
    title: 'DSMB Composition and Operating Procedures Not Specified',
    document_text:
      'A Data Safety Monitoring Board will be established to review safety data on a quarterly basis.',
    regulatory_text:
      'ICH E6(R2) Section 5.5.2: The sponsor should implement a system to manage quality throughout all stages of the trial process. The system should use a risk-based approach to quality management.',
    citation: 'ICH E6(R2) § 5.5.2, FDA GCP § 312.32',
    gap_analysis:
      'While a DSMB is mentioned, the protocol lacks critical details: member composition, expertise requirements, charter reference, meeting frequency, stopping rules, and escalation procedures.',
    suggested_fix:
      'Add a dedicated DSMB section specifying: (1) Minimum 3 members including biostatistician and clinician, (2) Reference to DSMB Charter v1.0, (3) Specific stopping rules for primary safety endpoints.',
    confidence: 'HIGH',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'find-003',
    document_id: 'doc-001',
    severity: 'major',
    status: 'accepted',
    section: 'Section 3.4 - Protocol Version Control',
    title: 'Protocol Version Dating Inconsistency',
    document_text:
      'This protocol (Version 2.1) supersedes all previous versions. Protocol Version 1.0 was approved on January 15, 2024.',
    regulatory_text:
      'ICH E6(R2) Section 6.0: The protocol should contain a statement on how protocol amendments will be handled and documented.',
    citation: 'ICH E6(R2) § 6.0',
    gap_analysis:
      'The protocol references Version 1.0 approval date but does not document Version 2.0 approval date, creating a gap in the version history audit trail required for regulatory submission.',
    suggested_fix:
      'Add complete version history table: Version 1.0 (Jan 15 2024, Initial), Version 2.0 (date, reason), Version 2.1 (current date, current rationale).',
    confidence: 'MEDIUM',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'find-004',
    document_id: 'doc-001',
    severity: 'major',
    status: 'pending',
    section: 'Section 9.2 - Statistical Analysis',
    title: 'Interim Analysis Plan Missing Power Re-estimation',
    document_text:
      'Two interim analyses are planned at 33% and 66% of target enrollment. Alpha spending will follow the O\'Brien-Fleming boundary.',
    regulatory_text:
      'ICH E9 Section 4.4: Any provision for interim analyses, alpha spending and group sequential methods, or adaptive designs should be pre-specified in the protocol and statistical analysis plan.',
    citation: 'ICH E9 § 4.4',
    gap_analysis:
      'Interim analyses are mentioned but the protocol lacks: (1) Blinded sample size re-estimation procedures, (2) Operational details for unblinded DMC review, (3) Criteria for early termination for efficacy or futility.',
    suggested_fix:
      'Expand Section 9.2 to include: blinded SSR methodology, DMC charter reference for unblinded review, and explicit futility boundaries (e.g., conditional power < 20%).',
    confidence: 'HIGH',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'find-005',
    document_id: 'doc-001',
    severity: 'minor',
    status: 'rejected',
    section: 'Section 1.2 - Background',
    title: 'Reference to Superseded Guideline Version',
    document_text: 'Per ICH E6 Good Clinical Practice guidelines (1996), all clinical trial activities must...',
    regulatory_text:
      'ICH E6(R2) was released in November 2016 and is the current operative guideline, superseding the original 1996 version.',
    citation: 'ICH E6(R2) (2016)',
    gap_analysis:
      'The protocol cites the original 1996 ICH E6 rather than the current ICH E6(R2) from 2016. While substantive requirements are similar, regulatory reviewers may flag this as insufficient due diligence.',
    suggested_fix: 'Update reference to: "ICH E6(R2) Good Clinical Practice Guidelines (2016, updated 2023)".',
    confidence: 'HIGH',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'find-006',
    document_id: 'doc-001',
    severity: 'minor',
    status: 'accepted',
    section: 'Section 12.1 - Appendices',
    title: 'Investigator CV Not Referenced in Protocol',
    document_text:
      'All investigators have been selected based on their qualifications and experience in the relevant therapeutic area.',
    regulatory_text:
      'ICH E6(R2) Section 8.2.10: Curriculum vitae and/or other relevant documents evidencing qualifications of investigator(s) and sub-investigator(s) should be included in the essential documents.',
    citation: 'ICH E6(R2) § 8.2.10',
    gap_analysis:
      'Protocol lacks explicit reference to investigator CVs as essential documents. Minor administrative gap but should be addressed for completeness.',
    suggested_fix: 'Add to Section 12.1: "Appendix F: Current CVs for Principal Investigator and all sub-investigators (ICH E6(R2) § 8.2.10)".',
    confidence: 'MEDIUM',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DUMMY_STATS = {
  critical: 2,
  major: 2,
  minor: 2,
  accepted: 2,
  rejected: 1,
  pending: 3,
};

export const DUMMY_AUDIT_LOGS = [
  {
    id: 'audit-001',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'finding_accepted',
    resource_type: 'finding',
    resource_id: 'find-003',
    details: { finding_title: 'Protocol Version Dating Inconsistency', document: 'Clinical Trial Protocol v2.1' },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-002',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'analysis_started',
    resource_type: 'document',
    resource_id: 'doc-001',
    details: { document: 'Clinical Trial Protocol v2.1', guidelines: ['ICH-E6', 'FDA-GCP'] },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-003',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'document_upload',
    resource_type: 'document',
    resource_id: 'doc-001',
    details: { document: 'Clinical Trial Protocol v2.1', file_size: '2.4 MB', pages: 48 },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-004',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'report_exported',
    resource_type: 'report',
    resource_id: 'rep-001',
    details: { document: 'ICH E6 Compliance Audit Report', format: 'PDF' },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-005',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'finding_rejected',
    resource_type: 'finding',
    resource_id: 'find-005',
    details: { finding_title: 'Reference to Superseded Guideline Version', document: 'Clinical Trial Protocol v2.1' },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-006',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'user_login',
    resource_type: 'session',
    resource_id: null,
    details: { browser: 'Chrome 120', os: 'macOS' },
    ip_address: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'audit-007',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'document_upload',
    resource_type: 'document',
    resource_id: 'doc-003',
    details: { document: 'ICH E6 Compliance Audit Report', file_size: '1.2 MB', pages: 32 },
    ip_address: '10.0.0.12',
    status: 'success',
  },
  {
    id: 'audit-008',
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    user: 'Dr. Sarah Mitchell',
    action: 'document_upload',
    resource_type: 'document',
    resource_id: 'doc-004',
    details: { document: 'FDA Label Review Package', file_size: '987 KB', pages: 22 },
    ip_address: '10.0.0.12',
    status: 'success',
  },
];

export const DUMMY_HISTORY = [
  {
    id: 'hist-001',
    action: 'accepted',
    document_name: 'Clinical Trial Protocol v2.1',
    finding_title: 'Protocol Version Dating Inconsistency',
    section: 'Section 3.4',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-002',
    action: 'rejected',
    document_name: 'Clinical Trial Protocol v2.1',
    finding_title: 'Reference to Superseded Guideline Version',
    section: 'Section 1.2',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-003',
    action: 'accepted',
    document_name: 'Clinical Trial Protocol v2.1',
    finding_title: 'Investigator CV Not Referenced in Protocol',
    section: 'Section 12.1',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-004',
    action: 'uploaded',
    document_name: 'Drug Safety Report Q3 2024',
    finding_title: null,
    section: null,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-005',
    action: 'exported',
    document_name: 'ICH E6 Compliance Audit Report',
    finding_title: null,
    section: null,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-006',
    action: 'analyzed',
    document_name: 'ICH E6 Compliance Audit Report',
    finding_title: null,
    section: null,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'hist-007',
    action: 'uploaded',
    document_name: 'FDA Label Review Package',
    finding_title: null,
    section: null,
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DUMMY_ANALYTICS = {
  total_documents: 24,
  avg_compliance_score: 82,
  time_saved_percentage: 68,
  critical_issues_found: 7,
  documents_by_month: [
    { month: 'Aug', count: 2 },
    { month: 'Sep', count: 4 },
    { month: 'Oct', count: 6 },
    { month: 'Nov', count: 8 },
    { month: 'Dec', count: 4 },
  ],
  compliance_trends: {
    completed: 18,
    processing: 3,
    failed: 2,
    uploaded: 1,
  },
};
